services:
  api:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.api
    init: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "3001:3001"
    env_file:
      - local.env
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cars_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data: 