services:
  api:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.api
    init: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "3000:3000"
    env_file:
      - local.env 